### ISSUE TITLE
Header and Footer Link Tweaks

### ISSUE THREAD

**Issue by allella** [codeforgreenville/hackgreenville-com#21]
I think the "Join Slack" is important enough for a header menu item.  HG is as much the Slack as it is promoting all the events.

In the footer, I think we satisfy the CFG hat-tip in #2 by having a "Contribute" link in the footer. That way anybody who wants to help can learn more at GitHub and they would see the project is supported by Code For Greenville based on the GitHub repo.

**Comment by allella** [comment]
Closes #2

**Comment by allella** [comment]
Close #2

**Comment by zach2825** [comment]
I completely agree that "Join Slack" and other important services to us should be more prominent. Like links to the repo, slack, api documentation, and meetup group links. I try to keep action items off the main nav. It just does not feel right to add them up there. We could create a services section on the homepage and about us page so that we can talk about more of our services and pad out the content on the homepage more so it made more information at a glance. 

I would like to present something like this, don't judge me on mockup abilities, it's rough but the main content could be on the top, then we have a services section, and eventually maybe a contact us form or whatever...

This is not how it would look. I'm not 100% sure we'd do to make it look good but the ideas there. 
![image](https://user-images.githubusercontent.com/4049321/70958806-52605300-2048-11ea-93f0-f67391a1bb63.png)

**Comment by allella** [comment]
I'm hip to the action buttons, but I think we could put them above the copy.  People are likely more interested in interacting with the site than reading our clever content anyway.

I'm open to ideas on the navigation, but I think the Slack community is important enough that we want it visible on most, if not all pages.  Do we have an example of a site that has a nice mix of navigation links and "call to action" links or buttons in the header?  I suspect mobile responsiveness will come into play too if we replaced the Slack nav links.

**Comment by allella** [comment]
I suppose we could just have a nav link called "Slack" or "Connect" and then have a dedicated page with info on how to join or login.

That would be

**Comment by allella** [comment]
Also, I meant to say that the [HackGreenville Meetup group](https://www.meetup.com/Hack-Greenville/) is likely too confusing to make a prominent item. It's only used by a few groups who didn't want to pay for a Meetup account and is a small fraction of the actual meetup groups and events we promote on the Orgs, Events, and Calendar page.

**Comment by allella** [comment]
Once [Chapter](https://github.com/freeCodeCamp/chapter/) is stable I'm expecting Code For Greenville can host and maintain a HackGreenville subdomain to offer free event registration to local meetup chapters who don't want to continue using meetup.com.

That would be an eventual tool / service to promote under the HG brand, but for now we don't have anything worth promoting on that side.

**Comment by allella** [comment]
I think we're pretty well representing the Slack in the header and footer. Closing #21
