### ISSUE TITLE
HTML/CSS cleanup

### ISSUE THREAD

**Issue by magoun** [codeforgreenville/hackgreenville-com#3]
The site utilizes the Now UI Kit from Creative Tim (free version), but the implementation isn't great. The navigation bar cobbles together elements from the UI Kit, vanilla Bootstrap and custom CSS to function on mobile. This should be cleaned up to be more robust. Keeping the UI Kit is NOT required, but the current functionality should not be broken.

**Comment by allella** [comment]
@magoun 
I installed npm and node on the production server and got an error so might eventually needs some help with getting that happy.

**Comment by allella** [comment]
@MarkMcDaniels 

Okay. So, I got npm and laravel-mix not crashing on
`npm run production`
only to realize the js/app.js and css/app.css are not referenced in the application.

Looks like all the CSS and JS is inlined in the blade templates.

So, this issue is related to your hover issue in that both probably should be moved into the laravel-mix way of doing things if we want to be Larvel-friendly.

**Comment by zach2825** [comment]
thanks for the work that you guys did I was able to rapidly put the bootstrap 4 framework in place. The variables have been started and the base app.blade.php file should be standard. 

That work is currently in the develop Branch

**Comment by zach2825** [comment]
Relates to #43
