### ISSUE TITLE
Create the contact us page

### ISSUE THREAD

**Issue by zach2825** [codeforgreenville/hackgreenville-com#46]
Maybe the pages contact form could send the contact to the slack community. We'll probably need to create a new channel for that content to live. that way people can be invited or removed from it. 

Send slack notifications.
https://laravel.com/docs/5.8/notifications#slack-notifications

**Comment by allella** [comment]
I've invited the admins of the Slack to follow this repo so we can get their input on the website-to-Slack issues.

**Comment by allella** [comment]
For instance, since we're on a free tier there may be a limit to the number of apps / integrations we can do without removing an existing integration.

**Comment by zach2825** [comment]
Good point. For the site we could use a "requests" channel or whatever the name is.

Maybe we could create a Greenville microservice that handles all the connectivity things. So all the other services can use that.

**Comment by allella** [comment]
Yeah, good question for webdood if/when he joins GitHub

**Comment by davebrothers** [comment]
@allella I have granted you the App Managers role. Would want to make sure we check with @soulfire86 about what is/isn't being used as I'm fairly out of that loop, but even just looking at that page I think there's some throwaway/sandboxy stuff from a bygone age. And if there's a limit to how many we can configure, it's no longer super apparent from the admin page.

**Comment by zach2825** [comment]
Looks like for the free slack account there is a limit of 10 apps.

https://slack.com/help/articles/115003205446
and on the top of this page.
https://app.slack.com/plans/T0420TN6E/

**Comment by davebrothers** [comment]
Thanks @zach2825 -- we're only at 7 even with possible bloat, so there's wiggle room.

**Comment by oliviasculley** [comment]
I'll look into this after I get some more work done on the events-api slack bot done.
The slack bot will need to be hosted on a subdomain or subdirectory in order to provide Slack with a proper callback target, so we'll need to coordinate in order to find the best way to host the bot on the hackgreenville site eventually. 
Hopefully I'll be able to have this soon since I've written a slack integration pretty similar to this before :smile: 
We can also look into using something like [hcaptcha](https://www.hcaptcha.com) to prevent spam submissions, which is completely free to use and pretty easy to integrate.

**Comment by allella** [comment]
Sounds good.  I imagine having this on Hackgreenville.com/subdir or HG subdomain will make sense if it's particular to the Hackgreenville Slack.

We'd have to hit up webdood for a subdomain, but a subdirectory should be fine too if it's not too complicated to integrated into the existing server.

What language is the bot likely to be?
