### ISSUE TITLE
Change join us on slack page.

### ISSUE THREAD

**Issue by zach2825** [codeforgreenville/hackgreenville-com#47]
Build the page as part of the site. and when people complete the form log the contact in the database and send a slack notification to a "requests" channel or something 

Prerequisite: #46 since we need the slack integration

**Comment by allella** [comment]
This would be something to chat with webdood about as he's fielding the requests at the moment.  He's not on this Github repo, but I'll ask him to join the conversation.

**Comment by zach2825** [comment]
Awesome thank you

**Comment by Soulfire86** [comment]
Hey, sorry was at Disney World.

I'm pretty open to whatever as far as invites go. currently they do come to me in Slack via TypeForm's integration, I could just as easily send them to a channel rather than just myself I suppose.

I don't necessarily see the benefit of redoing invites from scratch unless it's for educational purposes, but I'm not opposed by any means.

Though I believe someone else had mentioned using a Heroku script that auto invites people rather than screening them first.

**Comment by oliviasculley** [comment]
Just looking into this a little, it seems like a slack auto-invite bot really doable since [admin.users.invite](https://api.slack.com/methods/admin.users.invite) is built into the Slack API!
I can probably get this done pretty quickly after the contact us implementation is in since both actions are pretty similar :smile:
