### ISSUE TITLE
WWCode Greenville monthly Hack Nights are missing

### ISSUE THREAD

**Issue by pamelawoodbrowne** [codeforgreenville/hackgreenville-com#60]
It appears to be a problem with repeating events for [Women Who Code Greenville](https://www.meetup.com/Women-Who-Code-Greenville/events/) (Example: [1st Thursday hack nights](https://www.meetup.com/Women-Who-Code-Greenville/events/qjqhqrybchbkb/)). One time WWCode events are showing up except the most recently scheduled one on March 12th. The May 30th event doesn't show the updated title and description but that may be normal behavior for edited events.

**Comment by allella** [comment]
https://www.meetup.com/Women-Who-Code-Greenville/events/267817088/

**Comment by jeremywight** [comment]
I confirmed that the Hack Nights are being returned by the meetup API https://share.getcloudapp.com/p9u76xXv

**Comment by allella** [comment]
Here's the API endpoint.
https://www.meetup.com/meetup_api/docs/:urlname/events/#list

status
"cancelled", "upcoming", "past", "proposed", "suggested", or "draft"

See this issue for previous issues with API parameters
https://github.com/codeforgreenville/upstate_tech_cal_service/issues/15

**Comment by allella** [comment]
The Women Who Code events are showing in our API
https://events.openupstate.org/api/gtc

**Comment by allella** [comment]
https://events.openupstate.org/api/gtc?start_date=2018-01-01&end_date=2018-02-01

With start and end date

**Comment by jeremywight** [comment]
We've confirmed the proper events are being returned from the events API for this date range https://events.openupstate.org/api/gtc?start_date=2020-05-01&end_date=2020-06-01

**Comment by allella** [comment]
@zach2825 we triaged this issue on a Code For Greenville Zoom earlier this evening.

This is not limited to Women Who Code, since Code For Greenville and other May events are not showing on the [HG Calendar page.](https://hackgreenville.com/calendar).

However, the data is showing in the [Events API](https://github.com/codeforgreenville/upstate_tech_cal_service), as @jeremywight  and I posted above.  Also, one of the other applications that pulls from the Events API for [OpenWorks' dashboard ](https://joinopenworks.com/dashboard/meetups.php)is also showing the missing events for May. 

Since you're closest to the HG calendar we hoped you could take a look and see if there's a bug in the calendar module or some other obvious reason only a minority of the events are showing.  We see Synergy Mill and Wordpress and Upstate Dev Ops are showing, so perhaps it's only showing the events that are last in the list since things are starting with "S", "U", and "W"

**Comment by allella** [comment]
@zach2825  The missing events are showing on the [HG Events page](https://hackgreenville.com/events), so that's another point that the Events API is returning the correct info.

I guess Women Who Code would be last in the list, so IDK why only some are showing on the calendar.

**Comment by zach2825** [comment]
I'll look into this, thank you guys for checking the api side. I tried to add some intelligence to avoid duplicate entries that must breaking the import for some reason. I'll remove those checks they should not be needed anymore.

**Comment by zach2825** [comment]
The events seem to be in the database and they are being send to the calendar page I can see them in the source. I need to spend some more time to see why they're not showing up

**Comment by allella** [comment]
@pamelawoodbrowne 

@zach2825 updated the calendar.  Please test it out https://hackgreenville.com/calendar

Also, Pam, @jeremywight @zach2825  I notice some events have generic titles, like "Monthly Meetup" You think we should use the organization name + event title?

I know we have the Hackgreenville Meetup group that UpstatePHP and a couple other use, so using just the organization may not work, but the way it is makes it a bit unclear what some of the events are on the calendar

**Comment by pamelawoodbrowne** [comment]
@allella @zach2825 Weird - the [WWCode 1st Thursday hack nights](https://www.meetup.com/Women-Who-Code-Greenville/events/) are still missing and the canceled freeCodeCamp ones on the same nights are on the calendar. [FCC doesn't meet again until August.](https://www.meetup.com/Hack-Greenville/events/)
